// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/integrations/supabase/types';

const SUPABASE_URL = "https://luubdvuuxvtkheyhzepm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1dWJkdnV1eHZ0a2hleWh6ZXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzc4MTksImV4cCI6MjA2NDcxMzgxOX0.aS-if_zvAmLYW7Y3ySPYpU71zbB3ycV0pBDJpznkb5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);